spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak01.konturlabs.com/realms/test
          jwk-set-uri: https://keycloak01.konturlabs.com/realms/test/protocol/openid-connect/certs

konturApi:
  host: 'https://test-api.konturlabs.com/'

konturApps:
  host: 'https://test-apps.konturlabs.com/'

pdc:
  host: 'https://testemops.pdc.org'
  mapSrvHost: 'https://testapps.pdc.org'

staticdata:
  s3Folder: 'TEST QA/'

humanitarianCrisis:
  s3Folder: 'kontur_events/TEST QA/'

pdcProduct:
  s3Folder: 'products/TEST QA/'

aws:
  sqs:
    enabled: true

feign:
  client:
    config:
      default:
        defaultRequestHeaders:
          User-Agent: Event API TEST
