spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak01.konturlabs.com/auth/realms/dev
          jwk-set-uri: https://keycloak01.konturlabs.com/auth/realms/dev/protocol/openid-connect/certs

konturApi:
  host: 'https://test-api02.konturlabs.com/'

konturApps:
  host: 'https://test-apps02.konturlabs.com/'

pdc:
  host: 'https://testemops.pdc.org'
  mapSrvHost: 'https://testapps.pdc.org'

humanitarianCrisis:
  s3Folder: 'kontur_events/TEST DEV/'

staticdata:
  s3Folder: 'TEST DEV/'

scheduler:
  normalization:
    providers: gdacsAlert, gdacsAlertGeometry, firms.modis-c6, firms.suomi-npp-viirs-c2, firms.noaa-20-viirs-c2, kontur.events, pdcSqs
aws:
  sqs:
    enabled: true

feign:
  client:
    config:
      default:
        defaultRequestHeaders:
          User-Agent: Event API DEV
      auth:
        logger-level: HEADERS
