spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak01.kontur.io/realms/kontur
          jwk-set-uri: https://keycloak01.kontur.io/realms/kontur/protocol/openid-connect/certs

konturApi:
  host: 'https://api.kontur.io/'

konturApps:
  host: 'https://apps.kontur.io/'

pdc:
  host: 'https://emops.pdc.org/'
  mapSrvHost: 'https://apps.pdc.org'

staticdata:
  s3Folder: 'PROD/'

usgs:
  host: 'https://earthquake.usgs.gov'

humanitarianCrisis:
  s3Folder: 'kontur_events/PROD/'

aws:
  sqs:
    enabled: true

feign:
  client:
    config:
      default:
        defaultRequestHeaders:
          User-Agent: Event API PROD

scheduler:
  usgsEarthquakeImport:
    enable: true
