spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak01.konturlabs.com/realms/dev
          jwk-set-uri: https://keycloak01.konturlabs.com/realms/dev/protocol/openid-connect/certs

konturApi:
  host: 'https://test-api02.konturlabs.com/'

konturApps:
  host: 'https://test-apps02.konturlabs.com/'

pdc:
  host: 'https://testemops.pdc.org'
  mapSrvHost: 'https://testapps.pdc.org'

humanitarianCrisis:
  s3Folder: 'kontur_events/TEST DEV/'

mergeDecisions:
  s3Folder: 'merge_decisions/TEST DEV/'

staticdata:
  s3Folder: 'TEST DEV/'

aws:
  sqs:
    enabled: true

feign:
  client:
    config:
      default:
        defaultRequestHeaders:
          User-Agent: Event API DEV
      auth:
        logger-level: HEADERS
